{
 "title": "Wordpress",
 "description": "Custom dashboard для Grafana (Plugin PromPress for wordpress)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Общее количество запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prompress_request_peak_memory_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prompress_request_duration_seconds_count{status_code=\"200\"}[1m])) / sum(rate(prompress_request_duration_seconds_count{status_code=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее значение использования памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(prompress_request_peak_memory_sum[5m])) / sum(rate(prompress_request_peak_memory_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процентиль использования памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prompress_request_peak_memory_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Коды ответов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(prompress_request_count_total{status=~\"2..\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prompress_request_count_total{status=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}