{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Доступность подов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - sum by (pod)(kube_pod_start_time{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (pod) (kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\"})/max by (pod) (kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"memory\"})*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$namespace\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи прастранства $namespace",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} |= ``"
    }
   ]
  }
 ]
}