filebeat.inputs:
- type: log
  id: nginx-access
  paths:
    - /var/log/nginx/access.log
  enabled: true
  json.keys_under_root: true
  json.add_error_key: true
  processors:
    - dissect:
        tokenizer: "%{remote_addr} - %{remote_user} [%{+timestamp}] \"%{request}\" %{status} %{body_bytes_sent} \"%{http_referer}\" \"%{http_user_agent}\""
        field: "message"
        target_prefix: "nginx_access"
    - timestamp:
        field: "nginx_access.timestamp"
        layouts:
          - "02/Jan/2006:15:04:05 +0000"  # Формат времени в логе
        test:
          - "10/Oct/2023:14:55:36 +0000"
    - add_fields:
        fields:
          app: nginx-access
  index: "otus-nginx-access-logs-%{+yyyy.MM.dd}"
- type: log
  id: nginx
  paths:
    - /var/log/nginx/*.log
  enabled: true
  processors:
    - add_fields:
        fields:
          app: nginx

  index: "otus-nginx-logs-%{+yyyy.MM.dd}"

- type: log
  id: php-fpm
  paths:
    - /var/log/php*-fpm.log
  enabled: true
  processors:
    - add_fields:
        fields:
          app: php-fpm
  index: "otus-php-fpm-logs-%{+yyyy.MM.dd}"
- type: log
  id: mysql
  paths:
    - /var/log/mysql/*.log
  enabled: true
  processors:
    - add_fields:
        fields:
          app: "mysql"
  index: "otus-mysql-logs-%{+yyyy.MM.dd}"

- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.kibana:
setup.template.enabled: false
output.elasticsearch:
  hosts: ["https://192.168.2.14:9200"]
  preset: custom
  username: "****"
  password: "****"
  ssl.verification_mode: "none"
  indices:
    - index: "otus-nginx-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields:
          app: "nginx"
    - index: "otus-nginx-access-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields:
          app: "nginx-access"
    - index: "otus-mysql-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields:
          app: "mysql"
    - index: "otus-php-fpm-logs-%{+yyyy.MM.dd}"
      when.equals:
        fields:
          app: "php-fpm"
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
