server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: mysql
  static_configs:
  - targets:
      - localhost
    labels:
      job: mysql
      #NOTE: Need to be modified to scrape any additional logs of the system.
      __path__: /var/log/mysql/*
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      #NOTE: Need to be modified to scrape any additional logs of the system.
      __path__: /var/log/nginx/*      
